In [1]:
import pandas as pd
import datetime

In [2]:
file2_name = "daily_trading_info_2019-2020.xlsx"
file2 = pd.read_excel(file2_name, sheet_name = None)
company_index = []
company_index = list(file2.keys())[:]

In [3]:
print(len(company_index))

800

In [4]:
from talib import abstract

In [5]:
pd.read_excel(company_index[0]+".xlsx").iloc[:,:-1]

           date       open       high        low      close   volume
0    2014-01-02  21.309999  21.700001  21.230000  21.459999  5096443
1    2014-01-03  21.400000  21.450001  20.370001  20.790001  9945683
2    2014-01-06  20.680000  20.680000  20.219999  20.240000  5171376
3    2014-01-07  20.100000  20.250000  19.860001  20.000000  5364241
4    2014-01-08  20.000000  20.389999  20.000000  20.230000  5186841
...         ...        ...        ...        ...        ...      ...
1517 2020-03-25  24.600000  24.850000  24.500000  24.799999  7072723
1518 2020-03-26  24.620001  25.290001  24.580000  25.129999  8346083
1519 2020-03-27  25.320000  25.799999  25.150000  25.180000  8794212
1520 2020-03-30  25.150000  25.570000  24.950001  25.450001  8179292
1521 2020-03-31  25.500000  25.540001  25.150000  25.350000  5331630

[1522 rows x 6 columns]

In [5]:
df = pd.read_excel(company_index[0]+".xlsx").iloc[:,:-1]

In [6]:
inputs = {
    'open': df["open"],
    'high': df["high"],
    'low':  df["low"],
    'close': df["close"],
    'volume': df["volume"]
}
# uses close prices (default)
out1 = abstract.RSI(inputs, timeperiod=6)
#RSI一般是6,12,24
out2 = abstract.MACD(inputs)[0]
out3 = abstract.MOM(inputs, timeperiod=5)
out4, out5, out6 = abstract.BBANDS(inputs)#, timeperiod=5, nbdevup=2, nbdevdn=2, matype=0)
out7, out8 = abstract.STOCH(inputs)
out9 = abstract.ADX(inputs, timeperiod=14)
out10 = abstract.WILLR(inputs, timeperiod=14)
out11 = abstract.BETA(inputs, timeperiod=5)
out12 = abstract.TSF(inputs, timeperiod=14)
out13 = abstract.ROCP(inputs, timeperiod=10)
out14 = abstract.WMA(inputs, timeperiod=30)
out15 = abstract.OBV(inputs)

In [10]:
inputs = {
    'open': df["open"],
    'high': df["high"],
    'low':  df["low"],
    'close': df["close"],
    'volume': df["volume"]
}
pd.DataFrame(abstract.ROCP(inputs))

             0
0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
...        ...
1517 -0.057393
1518 -0.028229
1519 -0.006706
1520 -0.002743
1521  0.011169

[1522 rows x 1 columns]

In [21]:
pd.concat([df, pd.DataFrame(out1, columns=["RSI"])\
          , pd.DataFrame(out2, columns=["MACD"])\
          , pd.DataFrame(out3, columns=["MOM"])\
          , pd.DataFrame(out4, columns=["BBANDS_1"])\
          , pd.DataFrame(out5, columns=["BBANDS_2"])\
          , pd.DataFrame(out6, columns=["BBANDS_3"])\
          , pd.DataFrame(out7, columns=["KD_1"])\
          , pd.DataFrame(out8, columns=["KD_2"])\
          , pd.DataFrame(out9, columns=["ADX"])\
          , pd.DataFrame(out10, columns=["WILLR"])\
          , pd.DataFrame(out11, columns=["BETA"])\
          , pd.DataFrame(out12, columns=["TSF"])\
          , pd.DataFrame(out13, columns=["ROCP"])\
          , pd.DataFrame(out14, columns=["WMA"])\
          , pd.DataFrame(out15, columns=["OBV"])], axis=1).tail(30)

,date,open,high,low,close,volume,RSI,MACD,MOM,BBANDS_1,...,BBANDS_3,KD_1,KD_2,ADX,WILLR,BETA,TSF,ROCP,WMA,OBV
1492,2020-02-19,28.180000,28.180000,27.500000,27.510000,11951853,39.400653,0.108662,-0.369999,28.329171,...,27.074829,55.660380,45.751895,17.265942,-52.190472,0.784726,27.689450,-0.064604,27.953376,1.797164e+09
1493,2020-02-20,27.570000,27.780001,27.400000,27.709999,7103498,45.031030,0.083094,0.359999,28.297007,...,27.250993,43.115315,50.456820,17.492171,-48.380970,0.575862,27.423077,-0.062267,27.942666,1.804267e+09
1494,2020-02-21,27.700001,27.959999,27.500000,27.809999,9149642,47.933598,0.070093,0.320000,28.278072,...,27.397927,33.137587,43.971094,17.367916,-80.528052,0.579463,27.340439,-0.037050,27.939419,1.813417e+09
1495,2020-02-24,27.990000,28.000000,27.570000,27.610001,10197682,42.542305,0.043154,-0.480000,28.126166,...,27.357834,33.825484,36.692795,17.176343,-89.491482,0.613541,27.178132,-0.018834,27.923849,1.803219e+09
1496,2020-02-25,27.360001,27.950001,27.209999,27.570000,14340206,41.424079,0.018364,-0.500000,27.854564,...,27.429435,33.898924,33.620665,17.498111,-88.157878,0.471699,27.253736,-0.015357,27.906537,1.788879e+09
1497,2020-02-26,27.350000,27.400000,27.030001,27.049999,10990435,29.378000,-0.042748,-0.460001,28.077029,...,27.022970,20.350069,29.358159,18.033435,-99.324373,0.285140,27.266044,-0.029770,27.856258,1.777889e+09
1498,2020-02-27,27.090000,27.320000,26.799999,26.850000,9729770,25.901637,-0.106095,-0.859999,28.106659,...,26.649341,14.447295,22.898763,18.825118,-97.816545,0.342645,27.185824,-0.018282,27.794494,1.768159e+09
1499,2020-02-28,26.600000,26.980000,26.139999,26.139999,9994705,17.220703,-0.211156,-1.670000,28.121746,...,25.966254,2.076156,12.291173,20.295623,-100.000000,0.434432,26.839560,-0.049109,27.687720,1.758164e+09
1500,2020-03-02,26.209999,26.629999,26.150000,26.580000,7556099,33.736182,-0.255962,-1.030001,27.790756,...,25.885244,9.492054,8.671835,21.661092,-80.180167,-0.187202,26.660329,-0.053756,27.612107,1.765720e+09
1501,2020-03-03,26.650000,26.959999,26.530001,26.660000,8190728,36.500313,-0.281767,-0.910000,27.265865,...,26.046134,21.859758,11.142656,22.155482,-76.576569,0.742972,26.529670,-0.050232,27.543398,1.773911e+09
1502,2020-03-04,26.510000,26.629999,26.350000,26.530001,6135029,33.754646,-0.309145,-0.519999,27.018031,...,26.085969,32.876741,21.409518,22.837174,-82.432384,0.941890,26.308901,-0.035623,27.467957,1.767776e+09
1503,2020-03-05,26.620001,26.950001,26.510000,26.930000,9415058,48.154620,-0.295163,0.080000,27.077337,...,26.058663,56.122843,36.953114,22.744822,-64.414393,0.828957,26.254066,-0.028149,27.420473,1.777191e+09
1504,2020-03-06,26.760000,27.120001,26.680000,26.740000,7169981,42.845876,-0.296001,0.600000,26.968970,...,26.407030,62.641114,50.546899,22.292263,-72.972971,0.536909,26.268901,-0.038475,27.361247,1.770021e+09
1505,2020-03-09,26.650000,26.650000,26.150000,26.270000,8055042,32.281732,-0.330777,-0.309999,27.066472,...,26.185528,55.747866,58.170608,22.613784,-93.627401,0.915025,26.190440,-0.048533,27.272344,1.761966e+09
1506,2020-03-10,26.000000,26.360001,25.809999,26.290001,9665316,33.123749,-0.352659,-0.369999,27.063375,...,26.040626,36.612393,51.667124,23.325652,-78.082131,0.858206,26.078572,-0.046427,27.186796,1.771631e+09
1507,2020-03-11,26.320000,26.549999,26.209999,26.309999,7245463,34.106844,-0.364188,-0.220001,27.055927,...,25.960073,29.060133,40.473464,23.556660,-77.168955,1.083857,26.047802,-0.027357,27.106193,1.778877e+09
1508,2020-03-12,26.280001,26.280001,25.799999,25.860001,6234627,24.415512,-0.404968,-1.070000,26.851221,...,25.736779,26.451582,30.708036,24.271878,-97.272666,1.355839,25.952198,-0.036871,27.000559,1.772642e+09
1509,2020-03-13,25.020000,25.590000,24.860001,25.350000,9252071,17.610218,-0.472987,-1.389999,26.761075,...,25.270926,23.362585,26.291433,25.840998,-84.142403,1.516065,25.740001,-0.030222,26.866129,1.763390e+09
1510,2020-03-16,25.879999,26.750000,25.480000,25.520000,14479570,25.874561,-0.507327,-0.750000,26.647240,...,25.084761,22.280165,24.031444,25.185790,-74.015744,0.838231,25.643847,-0.039880,26.746968,1.777870e+09
1511,2020-03-17,25.110001,25.570000,24.700001,25.070000,9438372,19.622374,-0.564347,-1.220001,26.479475,...,24.764525,26.781226,24.141325,25.337648,-85.877898,0.740442,25.395275,-0.059640,26.604753,1.768431e+09
1512,2020-03-18,25.219999,25.360001,24.700001,24.809999,8503989,16.806696,-0.623331,-1.500000,26.045924,...,24.598077,19.445055,22.835482,25.478658,-95.454599,0.690267,25.102528,-0.064832,26.452237,1.759927e+09
1513,2020-03-19,24.639999,24.799999,24.000000,24.240000,8647230,12.200894,-0.707910,-1.620001,25.897547,...,24.098453,10.713931,18.980071,26.218831,-92.307702,0.708793,24.589341,-0.099889,26.272839,1.751280e+09
1514,2020-03-20,24.340000,24.639999,24.250000,24.490000,5754668,23.268267,-0.746165,-0.860001,25.719407,...,23.932592,10.637077,13.598688,26.906134,-84.294883,0.660958,24.287582,-0.084144,26.120989,1.757035e+09
1515,2020-03-23,24.200001,24.389999,24.020000,24.129999,5502230,19.106482,-0.796351,-1.390001,25.248902,...,23.847097,11.608547,10.986518,27.740489,-95.833361,0.959599,23.965934,-0.081462,25.955355,1.751532e+09
1516,2020-03-24,24.400000,24.490000,23.990000,24.340000,6528145,28.107628,-0.809844,-0.730000,24.873830,...,23.930169,17.215278,13.153634,28.320763,-88.817883,1.154906,23.764835,-0.074173,25.811892,1.758061e+09
1517,2020-03-25,24.600000,24.850000,24.500000,24.799999,7072723,44.376552,-0.774491,-0.010000,24.864930,...,23.935070,42.671193,23.831673,28.172719,-74.121432,1.186711,23.837692,-0.057393,25.705978,1.765133e+09
1518,2020-03-26,24.620001,25.290001,24.580000,25.129999,8346083,53.445830,-0.711642,0.889999,25.281749,...,23.874250,69.141853,43.009441,27.266750,-58.695678,0.486899,24.041648,-0.028229,25.627978,1.773479e+09
1519,2020-03-27,25.320000,25.799999,25.150000,25.180000,8794212,54.786225,-0.650302,0.690001,25.554341,...,23.877658,82.541335,64.784794,25.632338,-56.884042,0.938815,24.230329,-0.006706,25.557978,1.782274e+09
1520,2020-03-30,25.150000,25.570000,24.950001,25.450001,8179292,61.895378,-0.573295,1.320002,25.741788,...,24.218212,78.033717,76.572302,24.381172,-47.101418,0.929712,24.535604,-0.002743,25.510366,1.790453e+09
1521,2020-03-31,25.500000,25.540001,25.150000,25.350000,5331630,57.852526,-0.514406,1.010000,25.628032,...,24.735967,70.597883,77.057645,23.219375,-50.724620,0.752119,24.843516,0.011169,25.461978,1.785121e+09

In [8]:
for w in range(0, len(company_index)):
    df = pd.read_excel(company_index[w]+".xlsx")
    inputs = {
    'open': df["open"],
    'high': df["high"],
    'low':  df["low"],
    'close': df["close"],
    'volume': df["volume"]
    }
    # uses close prices (default)
    out1 = abstract.RSI(inputs, timeperiod=6)
    out2 = abstract.MACD(inputs)[0]
    out3 = abstract.MOM(inputs, timeperiod=5)
    out4, out5, out6 = abstract.BBANDS(inputs)
    out7, out8 = abstract.STOCH(inputs)
    out9 = abstract.ADX(inputs, timeperiod=14)
    out10 = abstract.WILLR(inputs, timeperiod=14)
    out11 = abstract.BETA(inputs, timeperiod=5)
    out12 = abstract.TSF(inputs, timeperiod=14)
    out13 = abstract.ROCP(inputs, timeperiod=10)
    out14 = abstract.WMA(inputs, timeperiod=30)
    out15 = abstract.OBV(inputs)
    a =  pd.DataFrame(out1, columns=["RSI"])
    b = pd.DataFrame(out2, columns=["MACD"])
    c = pd.DataFrame(out3, columns=["MOM"])
    d = pd.DataFrame(out4, columns=["BBANDS_1"])
    e = pd.DataFrame(out5, columns=["BBANDS_2"])
    f = pd.DataFrame(out6, columns=["BBANDS_3"])
    g = pd.DataFrame(out7, columns=["KD_1"])
    h = pd.DataFrame(out8, columns=["KD_2"])
    i = pd.DataFrame(out9, columns=["ADX"])
    j = pd.DataFrame(out10, columns=["WILLR"])
    k = pd.DataFrame(out11, columns=["BETA"])
    l = pd.DataFrame(out12, columns=["TSF"])
    m = pd.DataFrame(out13, columns=["ROCP"])
    n = pd.DataFrame(out14, columns=["WMA"])
    o = pd.DataFrame(out15, columns=["OBV"])
    pd.concat([df,a , b, c, d, e, f, g, h, i, j, k, l, m, n, o], axis=1).to_excel(company_index[w]+".xlsx", \
                                                                 sheet_name = company_index[w], index=False)
    if(w%100==0):
        print(w)

0
100

In [9]:
train_set = pd.read_excel("strategy_results_train.xlsx")

In [10]:
import copy

In [11]:
dataset = copy.deepcopy(train_set)

In [12]:
temp = []
for i in range(0, dataset.shape[0]):
    if(i%1000==0):
        print(i, datetime.datetime.now())
    trade_company = dataset.iloc[i][0].split("_")[0]
    trade_date    = dataset.iloc[i][0].split("_")[1]
    df = pd.read_excel(trade_company+".xlsx")
    trade_date_datetime = datetime.date(int(trade_date[:4]), int(trade_date[4:]), 1) - datetime.timedelta(days=1)
    lower_index = 0
    for index in range(0, df.shape[0]):
        if(df["date"].iloc[index]< trade_date_datetime):
            lower_index = index
        else:
            break
    temp.append(list(df.iloc[lower_index, :]))

0 2020-06-13 19:56:56.459441
1000 2020-06-13 20:06:53.732551
2000 2020-06-13 20:16:32.490694
3000 2020-06-13 20:26:16.794005
4000 2020-06-13 20:36:03.740670
5000 2020-06-13 20:45:35.848128
6000 2020-06-13 20:55:37.065852
7000 2020-06-13 21:05:00.887221
8000 2020-06-13 21:14:45.736976
9000 2020-06-13 21:24:53.307050
10000 2020-06-13 21:35:14.485767
11000 2020-06-13 21:44:36.053868
12000 2020-06-13 21:55:24.966484
13000 2020-06-13 22:05:58.397197
14000 2020-06-13 22:16:03.679706
15000 2020-06-13 22:26:03.986994
16000 2020-06-13 22:36:05.897066
17000 2020-06-13 22:46:03.831814
18000 2020-06-13 22:55:47.938634
19000 2020-06-13 23:05:58.944205
20000 2020-06-13 23:15:45.736532
21000 2020-06-13 23:25:49.208356
22000 2020-06-13 23:35:38.579131
23000 2020-06-13 23:45:30.338033
24000 2020-06-13 23:55:28.546590
25000 2020-06-14 00:05:13.002050
26000 2020-06-14 00:15:12.148331
27000 2020-06-14 00:24:25.145989
28000 2020-06-14 00:35:06.314944
29000 2020-06-14 00:44:48.856184
30000 2020-06-14 00:54:33.624229
31000 2020-06-14 01:03:16.715851

In [13]:
temp[1]

[Timestamp('2015-01-30 00:00:00'),
 22.98999977111816,
 23.19000053405762,
 22.51000022888184,
 22.57999992370605,
 7880595,
 nan,
 33.06997169532818,
 0.3066126570766059,
 -0.8600006103515696,
 24.46563604006088,
 23.32000007629394,
 22.17436411252701,
 4.780284417028589,
 23.95693785180033,
 22.02582053796641,
 -91.3792834129022,
 0.1204490481499062,
 23.04197814438369,
 -0.07572658036675448,
 23.30750539636099,
 209047450]

In [14]:
pd.DataFrame(temp).to_excel("train_output.xlsx", index=False)

In [15]:
testset = pd.read_excel("sampleSubmission.xlsx")

In [16]:
testset.head()

                   id  label
0  SHSE.600085_201901      0
1  SHSE.600085_201902      0
2  SHSE.600085_201903      0
3  SHSE.600085_201904      0
4  SHSE.600085_201905      0

In [17]:
temp = []
for i in range(0, testset.shape[0]):
    if(i%1000==0):
        print(i, datetime.datetime.now())
    trade_company = testset.iloc[i][0].split("_")[0]
    trade_date    = testset.iloc[i][0].split("_")[1]
    df = pd.read_excel(trade_company+".xlsx")
    trade_date_datetime = datetime.date(int(trade_date[:4]), int(trade_date[4:]), 1) - datetime.timedelta(days=1)
    lower_index = 0
    for index in range(0, df.shape[0]):
        if(df["date"].iloc[index]< trade_date_datetime):
            lower_index = index
        else:
            break
    if(lower_index==0):
        temp.append(dash = ["-","","","","","","","",""])
    else:
        temp.append(list(df.iloc[lower_index, :]))

0 2020-06-14 01:23:46.612310
1000 2020-06-14 01:35:07.213511
2000 2020-06-14 01:44:29.706855
3000 2020-06-14 01:54:02.895731
4000 2020-06-14 02:02:40.134367
5000 2020-06-14 02:12:44.247654
6000 2020-06-14 02:22:45.257615
7000 2020-06-14 02:32:19.776393
8000 2020-06-14 02:41:54.365439
9000 2020-06-14 02:51:19.747169
10000 2020-06-14 03:00:50.051925
11000 2020-06-14 03:08:59.595834

In [18]:
pd.DataFrame(temp).to_excel("test_output.xlsx", index=False)

In [19]:
temp[0]

[Timestamp('2018-12-28 00:00:00'),
 27.18000030517578,
 27.57999992370605,
 26.98999977111816,
 27.5,
 3575585,
 nan,
 43.92068949139151,
 -0.6240644552131265,
 0.6700000762939489,
 27.5820741327054,
 27.25800018310547,
 26.93392623350553,
 81.91660104251638,
 62.96045814106529,
 27.60884945804808,
 -66.5914347566257,
 1.002493591762495,
 26.38648360116139,
 -0.08363879405992797,
 28.37903222524992,
 1750766779]